/*
 * Copyright (c) 2023 Nordic Semiconductor ASA
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_SENSOR_NPM1300_CHARGER_H_
#define ZEPHYR_INCLUDE_DRIVERS_SENSOR_NPM1300_CHARGER_H_

#include <zephyr/drivers/sensor.h>

/* NPM1300 charger specific channels */
enum sensor_channel_npm1300_charger {
	SENSOR_CHAN_NPM1300_CHARGER_STATUS = SENSOR_CHAN_PRIV_START,
	SENSOR_CHAN_NPM1300_CHARGER_ERROR,
};

/* NPM1300 charger status masks */
#define NPM1300_CHARGER_STATUS_BATT_DETECT_MASK BIT(0)
#define NPM1300_CHARGER_STATUS_COMPLETED_MASK   BIT(1)
#define NPM1300_CHARGER_STATUS_TRICKLE_MASK     BIT(2)
#define NPM1300_CHARGER_STATUS_CONST_CURR_MASK  BIT(3)
#define NPM1300_CHARGER_STATUS_CONST_VOLT_MASK  BIT(4)

/* NPM1300 charger error masks */
#define NPM1300_CHARGER_ERROR_NTC_SENSOR_MASK      BIT(0)
#define NPM1300_CHARGER_ERROR_VBAT_LOW_MASK        BIT(2)
#define NPM1300_CHARGER_ERROR_CHARGE_TIMEOUT_MASK  BIT(5)
#define NPM1300_CHARGER_ERROR_TRICKLE_TIMEOUT_MASK BIT(6)

#endif
